//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.ServiceReferenceAW {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SELECT_HumanResources_Department_Result", Namespace="http://schemas.datacontract.org/2004/07/ProyectoWCF")]
    [System.SerializableAttribute()]
    public partial class SELECT_HumanResources_Department_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SELECT_Production_ProductCategory_Result", Namespace="http://schemas.datacontract.org/2004/07/ProyectoWCF")]
    [System.SerializableAttribute()]
    public partial class SELECT_Production_ProductCategory_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductCategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid rowguidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductCategoryID {
            get {
                return this.ProductCategoryIDField;
            }
            set {
                if ((this.ProductCategoryIDField.Equals(value) != true)) {
                    this.ProductCategoryIDField = value;
                    this.RaisePropertyChanged("ProductCategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid rowguid {
            get {
                return this.rowguidField;
            }
            set {
                if ((this.rowguidField.Equals(value) != true)) {
                    this.rowguidField = value;
                    this.RaisePropertyChanged("rowguid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SELECT_Production_UnitMeasure_Result", Namespace="http://schemas.datacontract.org/2004/07/ProyectoWCF")]
    [System.SerializableAttribute()]
    public partial class SELECT_Production_UnitMeasure_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitMeasureCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitMeasureCode {
            get {
                return this.UnitMeasureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitMeasureCodeField, value) != true)) {
                    this.UnitMeasureCodeField = value;
                    this.RaisePropertyChanged("UnitMeasureCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAW.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/DELETE_HumanResources_Department_ResultResponse")]
        void DELETE_HumanResources_Department_Result(short DepartamentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/DELETE_HumanResources_Department_ResultResponse")]
        System.Threading.Tasks.Task DELETE_HumanResources_Department_ResultAsync(short DepartamentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/DELETE_Production_ProductCategory_ResultResponse")]
        void DELETE_Production_ProductCategory_Result(int productCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/DELETE_Production_ProductCategory_ResultResponse")]
        System.Threading.Tasks.Task DELETE_Production_ProductCategory_ResultAsync(int productCategoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/DELETE_Production_UnitMeasure_ResultResponse")]
        void DELETE_Production_UnitMeasure_Result(string unitMeasureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DELETE_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/DELETE_Production_UnitMeasure_ResultResponse")]
        System.Threading.Tasks.Task DELETE_Production_UnitMeasure_ResultAsync(string unitMeasureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/INSERT_HumanResources_Department_ResultResponse")]
        void INSERT_HumanResources_Department_Result(string name, string groupName, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/INSERT_HumanResources_Department_ResultResponse")]
        System.Threading.Tasks.Task INSERT_HumanResources_Department_ResultAsync(string name, string groupName, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/INSERT_Production_ProductCategory_ResultResponse")]
        void INSERT_Production_ProductCategory_Result(string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/INSERT_Production_ProductCategory_ResultResponse")]
        System.Threading.Tasks.Task INSERT_Production_ProductCategory_ResultAsync(string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/INSERT_Production_UnitMeasure_ResultResponse")]
        void INSERT_Production_UnitMeasure_Result(string unitMeasureCode, string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/INSERT_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/INSERT_Production_UnitMeasure_ResultResponse")]
        System.Threading.Tasks.Task INSERT_Production_UnitMeasure_ResultAsync(string unitMeasureCode, string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_HumanResources_Departments", ReplyAction="http://tempuri.org/IService1/SELECT_HumanResources_DepartmentsResponse")]
        ProyectoMVC.ServiceReferenceAW.SELECT_HumanResources_Department_Result[] SELECT_HumanResources_Departments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_HumanResources_Departments", ReplyAction="http://tempuri.org/IService1/SELECT_HumanResources_DepartmentsResponse")]
        System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_HumanResources_Department_Result[]> SELECT_HumanResources_DepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_Production_ProductCategory", ReplyAction="http://tempuri.org/IService1/SELECT_Production_ProductCategoryResponse")]
        ProyectoMVC.ServiceReferenceAW.SELECT_Production_ProductCategory_Result[] SELECT_Production_ProductCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_Production_ProductCategory", ReplyAction="http://tempuri.org/IService1/SELECT_Production_ProductCategoryResponse")]
        System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_Production_ProductCategory_Result[]> SELECT_Production_ProductCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_Production_UnitMeasure", ReplyAction="http://tempuri.org/IService1/SELECT_Production_UnitMeasureResponse")]
        ProyectoMVC.ServiceReferenceAW.SELECT_Production_UnitMeasure_Result[] SELECT_Production_UnitMeasure();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SELECT_Production_UnitMeasure", ReplyAction="http://tempuri.org/IService1/SELECT_Production_UnitMeasureResponse")]
        System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_Production_UnitMeasure_Result[]> SELECT_Production_UnitMeasureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_HumanResources_Department_ResultResponse")]
        void UPDATE_HumanResources_Department_Result(short departmentID, string name, string groupName, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_HumanResources_Department_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_HumanResources_Department_ResultResponse")]
        System.Threading.Tasks.Task UPDATE_HumanResources_Department_ResultAsync(short departmentID, string name, string groupName, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_Production_ProductCategory_ResultResponse")]
        void UPDATE_Production_ProductCategory_Result(int productCategoryID, string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_Production_ProductCategory_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_Production_ProductCategory_ResultResponse")]
        System.Threading.Tasks.Task UPDATE_Production_ProductCategory_ResultAsync(int productCategoryID, string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_Production_UnitMeasure_ResultResponse")]
        void UPDATE_Production_UnitMeasure_Result(string unitMeasureCode, string name, System.DateTime modifiedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UPDATE_Production_UnitMeasure_Result", ReplyAction="http://tempuri.org/IService1/UPDATE_Production_UnitMeasure_ResultResponse")]
        System.Threading.Tasks.Task UPDATE_Production_UnitMeasure_ResultAsync(string unitMeasureCode, string name, System.DateTime modifiedDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProyectoMVC.ServiceReferenceAW.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProyectoMVC.ServiceReferenceAW.IService1>, ProyectoMVC.ServiceReferenceAW.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void DELETE_HumanResources_Department_Result(short DepartamentoID) {
            base.Channel.DELETE_HumanResources_Department_Result(DepartamentoID);
        }
        
        public System.Threading.Tasks.Task DELETE_HumanResources_Department_ResultAsync(short DepartamentoID) {
            return base.Channel.DELETE_HumanResources_Department_ResultAsync(DepartamentoID);
        }
        
        public void DELETE_Production_ProductCategory_Result(int productCategoryID) {
            base.Channel.DELETE_Production_ProductCategory_Result(productCategoryID);
        }
        
        public System.Threading.Tasks.Task DELETE_Production_ProductCategory_ResultAsync(int productCategoryID) {
            return base.Channel.DELETE_Production_ProductCategory_ResultAsync(productCategoryID);
        }
        
        public void DELETE_Production_UnitMeasure_Result(string unitMeasureCode) {
            base.Channel.DELETE_Production_UnitMeasure_Result(unitMeasureCode);
        }
        
        public System.Threading.Tasks.Task DELETE_Production_UnitMeasure_ResultAsync(string unitMeasureCode) {
            return base.Channel.DELETE_Production_UnitMeasure_ResultAsync(unitMeasureCode);
        }
        
        public void INSERT_HumanResources_Department_Result(string name, string groupName, System.DateTime modifiedDate) {
            base.Channel.INSERT_HumanResources_Department_Result(name, groupName, modifiedDate);
        }
        
        public System.Threading.Tasks.Task INSERT_HumanResources_Department_ResultAsync(string name, string groupName, System.DateTime modifiedDate) {
            return base.Channel.INSERT_HumanResources_Department_ResultAsync(name, groupName, modifiedDate);
        }
        
        public void INSERT_Production_ProductCategory_Result(string name, System.DateTime modifiedDate) {
            base.Channel.INSERT_Production_ProductCategory_Result(name, modifiedDate);
        }
        
        public System.Threading.Tasks.Task INSERT_Production_ProductCategory_ResultAsync(string name, System.DateTime modifiedDate) {
            return base.Channel.INSERT_Production_ProductCategory_ResultAsync(name, modifiedDate);
        }
        
        public void INSERT_Production_UnitMeasure_Result(string unitMeasureCode, string name, System.DateTime modifiedDate) {
            base.Channel.INSERT_Production_UnitMeasure_Result(unitMeasureCode, name, modifiedDate);
        }
        
        public System.Threading.Tasks.Task INSERT_Production_UnitMeasure_ResultAsync(string unitMeasureCode, string name, System.DateTime modifiedDate) {
            return base.Channel.INSERT_Production_UnitMeasure_ResultAsync(unitMeasureCode, name, modifiedDate);
        }
        
        public ProyectoMVC.ServiceReferenceAW.SELECT_HumanResources_Department_Result[] SELECT_HumanResources_Departments() {
            return base.Channel.SELECT_HumanResources_Departments();
        }
        
        public System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_HumanResources_Department_Result[]> SELECT_HumanResources_DepartmentsAsync() {
            return base.Channel.SELECT_HumanResources_DepartmentsAsync();
        }
        
        public ProyectoMVC.ServiceReferenceAW.SELECT_Production_ProductCategory_Result[] SELECT_Production_ProductCategory() {
            return base.Channel.SELECT_Production_ProductCategory();
        }
        
        public System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_Production_ProductCategory_Result[]> SELECT_Production_ProductCategoryAsync() {
            return base.Channel.SELECT_Production_ProductCategoryAsync();
        }
        
        public ProyectoMVC.ServiceReferenceAW.SELECT_Production_UnitMeasure_Result[] SELECT_Production_UnitMeasure() {
            return base.Channel.SELECT_Production_UnitMeasure();
        }
        
        public System.Threading.Tasks.Task<ProyectoMVC.ServiceReferenceAW.SELECT_Production_UnitMeasure_Result[]> SELECT_Production_UnitMeasureAsync() {
            return base.Channel.SELECT_Production_UnitMeasureAsync();
        }
        
        public void UPDATE_HumanResources_Department_Result(short departmentID, string name, string groupName, System.DateTime modifiedDate) {
            base.Channel.UPDATE_HumanResources_Department_Result(departmentID, name, groupName, modifiedDate);
        }
        
        public System.Threading.Tasks.Task UPDATE_HumanResources_Department_ResultAsync(short departmentID, string name, string groupName, System.DateTime modifiedDate) {
            return base.Channel.UPDATE_HumanResources_Department_ResultAsync(departmentID, name, groupName, modifiedDate);
        }
        
        public void UPDATE_Production_ProductCategory_Result(int productCategoryID, string name, System.DateTime modifiedDate) {
            base.Channel.UPDATE_Production_ProductCategory_Result(productCategoryID, name, modifiedDate);
        }
        
        public System.Threading.Tasks.Task UPDATE_Production_ProductCategory_ResultAsync(int productCategoryID, string name, System.DateTime modifiedDate) {
            return base.Channel.UPDATE_Production_ProductCategory_ResultAsync(productCategoryID, name, modifiedDate);
        }
        
        public void UPDATE_Production_UnitMeasure_Result(string unitMeasureCode, string name, System.DateTime modifiedDate) {
            base.Channel.UPDATE_Production_UnitMeasure_Result(unitMeasureCode, name, modifiedDate);
        }
        
        public System.Threading.Tasks.Task UPDATE_Production_UnitMeasure_ResultAsync(string unitMeasureCode, string name, System.DateTime modifiedDate) {
            return base.Channel.UPDATE_Production_UnitMeasure_ResultAsync(unitMeasureCode, name, modifiedDate);
        }
    }
}
